import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  hy: {
    home: "Գլխավոր", catalog: "Կատալոգ", academy: "AUREVIS Academy", benefits: "HoReCa բոնուսներ",
    account: "Իմ հաշիվը", login: "Մուտք / Գրանցում", balance: "Հաշվեկշիռ",
    heroEyebrow: "ՀԱՅԱՍՏԱՆՈՒՄ ԱՌԱՋԻՆ ՄԻԱՍՆԱԿԱՆ ՊՐՈՖԵՍԻՈՆԱԼ HORECA ՀԱՐԹԱԿԸ",
    heroTitleA: "Համից՝ մինչև", heroTitleB: "յուրահատուկ ըմպելիք։",
    heroText: "Պրեմիում օշարակներ, մրգային պյուրեներ և ամբողջական HoReCa լուծումներ՝ սրճարանների, ռեստորանների, հյուրանոցների և հրուշակեղենի արտադրամասերի համար։",
    openCatalog: "Բացել կատալոգը", becomePartner: "Դառնալ HoReCa գործընկեր",
    syrupFlavors: "Օշարակի համ", purees: "Մրգային պյուրե", free: "Անվճար", delivery: "Առաքում Հայաստանում",
    unifiedBalance: "Միասնական հաշվեկշիռ", quality: "Պրեմիում որակ", stable: "Կայուն համ և արդյունք",
    recipes: "Բաղադրատոմսեր և խորհուրդներ", profitTools: "Շահույթի գործիքներ", costProfit: "Ինքնարժեք և շահույթ",
    freeDelivery: "Անվճար առաքում", allArmenia: "Ամբողջ Հայաստանում",
    partnershipTitle: "Ոչ միայն ապրանք։ Ամբողջական HoReCa գործընկերություն։",
    partnershipText: "Պատվերներ, Wallet, Bonus, Academy և սարքավորումներ՝ մեկ միասնական հարթակում։",
    learnBenefits: "Տեսնել HoReCa բոնուսները",
    benefitsEyebrow: "AUREVIS HORECA PARTNERSHIP", benefitsTitle: "Ինչո՞ւ աշխատել AUREVIS-ի հետ",
    benefitsLead: "Ծրագիրը նախատեսված է հաստատված սրճարանների, ռեստորանների, հյուրանոցների և այլ HoReCa գործընկերների համար։ Այս էջը բաց է բոլոր այցելուների համար։",
    iceTitle: "5 կգ սառույց՝ յուրաքանչյուր շշի հետ", iceText: "Յուրաքանչյուր գնված AUREVIS օշարակի կամ պյուրեի մեկ շշի հետ ստացեք 5 կգ սառույց նվեր։",
    cashbackTitle: "Cashback յուրաքանչյուր գնումից", cashbackText: "Cashback-ը կուտակվում է միասնական Bonus Wallet-ում և կարող է օգտագործվել ապրանքների կամ սարքավորումների համար։",
    giftsTitle: "Նվերներ յուրաքանչյուր 3 ամիսը մեկ", giftsText: "Ակտիվ HoReCa գործընկերների համար՝ պարբերական հատուկ նվերներ և գործիքներ։",
    equipmentTitle: "Սարքավորումների ծրագիր", equipmentText: "Blender, հյութաքամիչ, shaker, գդալներ, squeezer, strainer և այլ պրոֆեսիոնալ գործիքներ։",
    levelsTitle: "HoReCa գործընկերային մակարդակներ", levelsText: "Ավելի ակտիվ համագործակցությունը բացում է ավելի բարձր cashback և նոր առավելություններ։",
    bronze: "Bronze", silver: "Silver", gold: "Gold", platinum: "Platinum", cashback: "cashback",
    eligibility: "Բոնուսները ակտիվանում են միայն AUREVIS-ի կողմից հաստատված HoReCa հաշվի համար։",
    joinProgram: "Միանալ HoReCa ծրագրին", myBonuses: "Իմ բոնուսները",
    catalogTitle: "Պրոֆեսիոնալ կատալոգ", catalogLead: "Պրեմիում օշարակներ, մրգային պյուրեներ և HoReCa լուծումներ՝ մեկ վայրում։",
    searchPlaceholder: "Փնտրել՝ Mojito, Vanilla, Raspberry...", all: "Բոլորը", loading: "Բեռնվում է...", product: "ապրանք",
    added: "Ավելացված է ✓", add: "+ Ավելացնել", details: "Սեղմել՝ մանրամասները տեսնելու համար", close: "Փակել",
    productDescription: "Պրոֆեսիոնալ AUREVIS արտադրանք՝ սրճարանների, ռեստորանների և HoReCa նախագծերի համար։",
    volume: "Ծավալ", price: "Գին", quantity: "Քանակ", decrease: "Պակասեցնել", addToCart: "Ավելացնել զամբյուղ",
    noProducts: "Ապրանք չի գտնվել", changeSearch: "Փոխիր որոնման բառը կամ ընտրիր այլ բաժին։",
    categorySyrups: "Օշարակներ", categoryPurees: "Պյուրեներ", categoryBakery: "Խմորեղեն", categoryDesserts: "Դեսերտներ",
    categoryBread: "Հաց", categoryEquipment: "Սարքավորումներ", categoryBarTools: "Բար գործիքներ", categoryOther: "Այլ ապրանքներ",
    academyTitleA: "Բաղադրատոմսից՝", academyTitleB: "մինչև իրական շահույթ", academyLead: "Հաշվարկիր յուրաքանչյուր բաժակի ինքնարժեքը, վաճառքի շահույթը և մեկ շշից ստացվող ամբողջ եկամուտը։",
    preciseDose: "Ճշգրիտ չափաբաժին", profitCalculation: "Շահույթի հաշվարկ", businessControl: "Բիզնես վերահսկում",
    businessCalculator: "ԲԻԶՆԵՍ ՀԱՇՎԻՉ", enterData: "Մուտքագրիր տվյալները", pureeDose: "Պյուրեի չափաբաժին", cupPrice: "Մեկ բաժակի վաճառքի գին",
    calculationBasis: "Հաշվարկի հիմքը", pureePrice: "Պյուրեի գին", additionalCost: "Լրացուցիչ ծախս", calculationResult: "ՀԱՇՎԱՐԿԻ ԱՐԴՅՈՒՆՔ",
    businessMetrics: "Քո բիզնեսի ցուցանիշները", fromBottle: "Մեկ շշից", cups: "բաժակ", cupCost: "Մեկ բաժակի ինքնարժեք",
    includingCosts: "ներառյալ լրացուցիչ ծախսը", cupProfit: "Շահույթ մեկ բաժակից", perCup: "վաճառքի յուրաքանչյուր բաժակից", bottleProfit: "Ընդհանուր շահույթ մեկ շշից", fromSales: "բաժակի վաճառքից",
    cartTitle: "Զամբյուղ", cartEmpty: "Զամբյուղը դատարկ է", orderSummary: "Պատվերի ամփոփում", total: "Ընդհանուր",
    signInToOrder: "Պատվիրելու համար մուտք գործիր կամ գրանցվիր։", phone: "Հեռախոս", address: "Առաքման հասցե", note: "Նշում",
    confirmOrder: "Հաստատել պատվերը", sending: "Ուղարկվում է…", viewOrders: "Դիտել իմ պատվերները",
    horecaOrderBenefits: "Քո HoReCa բոնուսները", iceGift: "սառույց նվեր", estimatedCashback: "կանխատեսվող cashback",
  },
  ru: {
    home: "Главная", catalog: "Каталог", academy: "AUREVIS Academy", benefits: "HoReCa бонусы",
    account: "Мой аккаунт", login: "Вход / Регистрация", balance: "Баланс",
    heroEyebrow: "ПЕРВАЯ ЕДИНАЯ ПРОФЕССИОНАЛЬНАЯ HORECA-ПЛАТФОРМА В АРМЕНИИ",
    heroTitleA: "От вкуса — к", heroTitleB: "уникальному напитку.",
    heroText: "Премиальные сиропы, фруктовые пюре и комплексные HoReCa-решения для кафе, ресторанов, гостиниц и кондитерских производств.",
    openCatalog: "Открыть каталог", becomePartner: "Стать HoReCa-партнёром",
    syrupFlavors: "Вкусов сиропа", purees: "Фруктовых пюре", free: "Бесплатно", delivery: "Доставка по Армении",
    unifiedBalance: "Единый баланс", quality: "Премиальное качество", stable: "Стабильный вкус и результат",
    recipes: "Рецепты и рекомендации", profitTools: "Инструменты прибыли", costProfit: "Себестоимость и прибыль",
    freeDelivery: "Бесплатная доставка", allArmenia: "По всей Армении",
    partnershipTitle: "Не просто продукт. Полное HoReCa-партнёрство.",
    partnershipText: "Заказы, Wallet, Bonus, Academy и оборудование — на одной платформе.",
    learnBenefits: "Посмотреть HoReCa бонусы",
    benefitsEyebrow: "ПАРТНЁРСТВО AUREVIS HORECA", benefitsTitle: "Почему стоит работать с AUREVIS",
    benefitsLead: "Программа предназначена для одобренных кафе, ресторанов, гостиниц и других HoReCa-партнёров. Эта страница доступна всем посетителям.",
    iceTitle: "5 кг льда с каждой бутылкой", iceText: "Получайте 5 кг льда в подарок с каждой купленной бутылкой сиропа или пюре AUREVIS.",
    cashbackTitle: "Cashback с каждой покупки", cashbackText: "Cashback накапливается в едином Bonus Wallet и используется на продукты или оборудование.",
    giftsTitle: "Подарки каждые 3 месяца", giftsText: "Регулярные специальные подарки и инструменты для активных HoReCa-партнёров.",
    equipmentTitle: "Программа оборудования", equipmentText: "Блендер, соковыжималка, шейкер, ложки, сквизер, стрейнер и другие профессиональные инструменты.",
    levelsTitle: "Уровни HoReCa-партнёрства", levelsText: "Более активное сотрудничество открывает повышенный cashback и новые преимущества.",
    bronze: "Bronze", silver: "Silver", gold: "Gold", platinum: "Platinum", cashback: "cashback",
    eligibility: "Бонусы активируются только для HoReCa-аккаунта, одобренного AUREVIS.",
    joinProgram: "Присоединиться к HoReCa", myBonuses: "Мои бонусы",
    catalogTitle: "Профессиональный каталог", catalogLead: "Премиальные сиропы, фруктовые пюре и HoReCa-решения в одном месте.",
    searchPlaceholder: "Поиск: Mojito, Vanilla, Raspberry...", all: "Все", loading: "Загрузка...", product: "товаров",
    added: "Добавлено ✓", add: "+ Добавить", details: "Нажмите, чтобы посмотреть детали", close: "Закрыть",
    productDescription: "Профессиональный продукт AUREVIS для кафе, ресторанов и HoReCa-проектов.",
    volume: "Объём", price: "Цена", quantity: "Количество", decrease: "Уменьшить", addToCart: "Добавить в корзину",
    noProducts: "Товары не найдены", changeSearch: "Измените запрос или выберите другой раздел.",
    categorySyrups: "Сиропы", categoryPurees: "Пюре", categoryBakery: "Выпечка", categoryDesserts: "Десерты",
    categoryBread: "Хлеб", categoryEquipment: "Оборудование", categoryBarTools: "Барные инструменты", categoryOther: "Другие товары",
    academyTitleA: "От рецепта —", academyTitleB: "к реальной прибыли", academyLead: "Рассчитайте себестоимость порции, прибыль с продажи и общий доход с одной бутылки.",
    preciseDose: "Точная дозировка", profitCalculation: "Расчёт прибыли", businessControl: "Контроль бизнеса",
    businessCalculator: "БИЗНЕС-КАЛЬКУЛЯТОР", enterData: "Введите данные", pureeDose: "Порция пюре", cupPrice: "Цена продажи порции",
    calculationBasis: "Основа расчёта", pureePrice: "Цена пюре", additionalCost: "Дополнительные расходы", calculationResult: "РЕЗУЛЬТАТ РАСЧЁТА",
    businessMetrics: "Показатели вашего бизнеса", fromBottle: "С одной бутылки", cups: "порций", cupCost: "Себестоимость порции",
    includingCosts: "с учётом дополнительных расходов", cupProfit: "Прибыль с порции", perCup: "с каждой проданной порции", bottleProfit: "Общая прибыль с бутылки", fromSales: "проданных порций",
    cartTitle: "Корзина", cartEmpty: "Корзина пуста", orderSummary: "Итоги заказа", total: "Итого",
    signInToOrder: "Для заказа войдите или зарегистрируйтесь.", phone: "Телефон", address: "Адрес доставки", note: "Примечание",
    confirmOrder: "Подтвердить заказ", sending: "Отправляется…", viewOrders: "Мои заказы",
    horecaOrderBenefits: "Ваши HoReCa бонусы", iceGift: "льда в подарок", estimatedCashback: "ожидаемый cashback",
  },
  en: {
    home: "Home", catalog: "Catalog", academy: "AUREVIS Academy", benefits: "HoReCa benefits",
    account: "My account", login: "Sign in / Register", balance: "Balance",
    heroEyebrow: "ARMENIA'S FIRST UNIFIED PROFESSIONAL HORECA PLATFORM",
    heroTitleA: "From flavor to", heroTitleB: "a signature drink.",
    heroText: "Premium syrups, fruit purées and complete HoReCa solutions for cafés, restaurants, hotels and pastry businesses.",
    openCatalog: "Open catalog", becomePartner: "Become a HoReCa partner",
    syrupFlavors: "Syrup flavors", purees: "Fruit purées", free: "Free", delivery: "Delivery across Armenia",
    unifiedBalance: "Unified balance", quality: "Premium quality", stable: "Consistent flavor and results",
    recipes: "Recipes and guidance", profitTools: "Profit tools", costProfit: "Cost and profit",
    freeDelivery: "Free delivery", allArmenia: "Across Armenia",
    partnershipTitle: "More than products. A complete HoReCa partnership.",
    partnershipText: "Orders, Wallet, Bonus, Academy and equipment on one unified platform.",
    learnBenefits: "View HoReCa benefits",
    benefitsEyebrow: "AUREVIS HORECA PARTNERSHIP", benefitsTitle: "Why work with AUREVIS",
    benefitsLead: "The program is for approved cafés, restaurants, hotels and other HoReCa partners. This page is public for every visitor.",
    iceTitle: "5 kg of ice with every bottle", iceText: "Receive 5 kg of ice as a gift with every bottle of AUREVIS syrup or purée purchased.",
    cashbackTitle: "Cashback on every purchase", cashbackText: "Cashback accumulates in one Bonus Wallet and can be used for products or equipment.",
    giftsTitle: "Gifts every 3 months", giftsText: "Regular special gifts and tools for active HoReCa partners.",
    equipmentTitle: "Equipment program", equipmentText: "Blender, juicer, shaker, spoons, squeezer, strainer and other professional tools.",
    levelsTitle: "HoReCa partnership levels", levelsText: "More active cooperation unlocks higher cashback and additional benefits.",
    bronze: "Bronze", silver: "Silver", gold: "Gold", platinum: "Platinum", cashback: "cashback",
    eligibility: "Benefits activate only for a HoReCa account approved by AUREVIS.",
    joinProgram: "Join the HoReCa program", myBonuses: "My bonuses",
    catalogTitle: "Professional catalog", catalogLead: "Premium syrups, fruit purées and HoReCa solutions in one place.",
    searchPlaceholder: "Search: Mojito, Vanilla, Raspberry...", all: "All", loading: "Loading...", product: "products",
    added: "Added ✓", add: "+ Add", details: "Click to view details", close: "Close",
    productDescription: "Professional AUREVIS product for cafés, restaurants and HoReCa projects.",
    volume: "Volume", price: "Price", quantity: "Quantity", decrease: "Decrease", addToCart: "Add to cart",
    noProducts: "No products found", changeSearch: "Change your search or choose another category.",
    categorySyrups: "Syrups", categoryPurees: "Purées", categoryBakery: "Bakery", categoryDesserts: "Desserts",
    categoryBread: "Bread", categoryEquipment: "Equipment", categoryBarTools: "Bar tools", categoryOther: "Other products",
    academyTitleA: "From recipe", academyTitleB: "to real profit", academyLead: "Calculate the cost per serving, sales profit and total income from one bottle.",
    preciseDose: "Precise dosage", profitCalculation: "Profit calculation", businessControl: "Business control",
    businessCalculator: "BUSINESS CALCULATOR", enterData: "Enter your data", pureeDose: "Purée dosage", cupPrice: "Selling price per cup",
    calculationBasis: "Calculation basis", pureePrice: "Purée price", additionalCost: "Additional cost", calculationResult: "CALCULATION RESULT",
    businessMetrics: "Your business metrics", fromBottle: "From one bottle", cups: "cups", cupCost: "Cost per cup",
    includingCosts: "including additional costs", cupProfit: "Profit per cup", perCup: "from each cup sold", bottleProfit: "Total profit per bottle", fromSales: "cups sold",
    cartTitle: "Cart", cartEmpty: "Your cart is empty", orderSummary: "Order summary", total: "Total",
    signInToOrder: "Sign in or register to place an order.", phone: "Phone", address: "Delivery address", note: "Note",
    confirmOrder: "Confirm order", sending: "Sending…", viewOrders: "View my orders",
    horecaOrderBenefits: "Your HoReCa benefits", iceGift: "ice gift", estimatedCashback: "estimated cashback",
  },
  ka: {
    home: "მთავარი", catalog: "კატალოგი", academy: "AUREVIS Academy", benefits: "HoReCa ბონუსები",
    account: "ჩემი ანგარიში", login: "შესვლა / რეგისტრაცია", balance: "ბალანსი",
    heroEyebrow: "პირველი ერთიანი პროფესიონალური HORECA პლატფორმა სომხეთში",
    heroTitleA: "გემოდან —", heroTitleB: "უნიკალურ სასმელამდე.",
    heroText: "პრემიუმ სიროფები, ხილის პიურეები და სრული HoReCa გადაწყვეტილებები კაფეებისთვის, რესტორნებისთვის, სასტუმროებისა და საკონდიტროებისთვის.",
    openCatalog: "კატალოგის გახსნა", becomePartner: "გახდი HoReCa პარტნიორი",
    syrupFlavors: "სიროფის გემო", purees: "ხილის პიურე", free: "უფასო", delivery: "მიწოდება სომხეთში",
    unifiedBalance: "ერთიანი ბალანსი", quality: "პრემიუმ ხარისხი", stable: "სტაბილური გემო და შედეგი",
    recipes: "რეცეპტები და რჩევები", profitTools: "მოგების ხელსაწყოები", costProfit: "თვითღირებულება და მოგება",
    freeDelivery: "უფასო მიწოდება", allArmenia: "მთელ სომხეთში",
    partnershipTitle: "არა მხოლოდ პროდუქტი. სრული HoReCa პარტნიორობა.",
    partnershipText: "შეკვეთები, Wallet, Bonus, Academy და აღჭურვილობა ერთ პლატფორმაზე.",
    learnBenefits: "HoReCa ბონუსების ნახვა",
    benefitsEyebrow: "AUREVIS HORECA პარტნიორობა", benefitsTitle: "რატომ უნდა ითანამშრომლოთ AUREVIS-თან",
    benefitsLead: "პროგრამა განკუთვნილია დამტკიცებული კაფეების, რესტორნების, სასტუმროებისა და სხვა HoReCa პარტნიორებისთვის. გვერდი ხელმისაწვდომია ყველა სტუმრისთვის.",
    iceTitle: "5 კგ ყინული ყოველ ბოთლზე", iceText: "მიიღეთ 5 კგ ყინული საჩუქრად AUREVIS-ის სიროფის ან პიურეს თითოეულ შეძენილ ბოთლზე.",
    cashbackTitle: "Cashback ყოველ შენაძენზე", cashbackText: "Cashback გროვდება ერთიან Bonus Wallet-ში და გამოიყენება პროდუქტებზე ან აღჭურვილობაზე.",
    giftsTitle: "საჩუქრები ყოველ 3 თვეში", giftsText: "რეგულარული სპეციალური საჩუქრები და ხელსაწყოები აქტიური HoReCa პარტნიორებისთვის.",
    equipmentTitle: "აღჭურვილობის პროგრამა", equipmentText: "ბლენდერი, წვენსაწური, შეიკერი, კოვზები, სკვიზერი, სტრეინერი და სხვა პროფესიონალური ხელსაწყოები.",
    levelsTitle: "HoReCa პარტნიორობის დონეები", levelsText: "უფრო აქტიური თანამშრომლობა ზრდის cashback-ს და ხსნის ახალ უპირატესობებს.",
    bronze: "Bronze", silver: "Silver", gold: "Gold", platinum: "Platinum", cashback: "cashback",
    eligibility: "ბონუსები აქტიურდება მხოლოდ AUREVIS-ის მიერ დამტკიცებული HoReCa ანგარიშისთვის.",
    joinProgram: "შეუერთდი HoReCa პროგრამას", myBonuses: "ჩემი ბონუსები",
    catalogTitle: "პროფესიონალური კატალოგი", catalogLead: "პრემიუმ სიროფები, ხილის პიურეები და HoReCa გადაწყვეტილებები ერთ სივრცეში.",
    searchPlaceholder: "ძიება: Mojito, Vanilla, Raspberry...", all: "ყველა", loading: "იტვირთება...", product: "პროდუქტი",
    added: "დამატებულია ✓", add: "+ დამატება", details: "დააჭირეთ დეტალების სანახავად", close: "დახურვა",
    productDescription: "AUREVIS-ის პროფესიონალური პროდუქტი კაფეებისთვის, რესტორნებისა და HoReCa პროექტებისთვის.",
    volume: "მოცულობა", price: "ფასი", quantity: "რაოდენობა", decrease: "შემცირება", addToCart: "კალათაში დამატება",
    noProducts: "პროდუქტი ვერ მოიძებნა", changeSearch: "შეცვალეთ ძიება ან აირჩიეთ სხვა კატეგორია.",
    categorySyrups: "სიროფები", categoryPurees: "პიურეები", categoryBakery: "ცომეული", categoryDesserts: "დესერტები",
    categoryBread: "პური", categoryEquipment: "აღჭურვილობა", categoryBarTools: "ბარის ხელსაწყოები", categoryOther: "სხვა პროდუქტები",
    academyTitleA: "რეცეპტიდან —", academyTitleB: "რეალურ მოგებამდე", academyLead: "გამოთვალეთ თითოეული ჭიქის თვითღირებულება, გაყიდვის მოგება და ერთი ბოთლიდან მიღებული სრული შემოსავალი.",
    preciseDose: "ზუსტი დოზირება", profitCalculation: "მოგების გამოთვლა", businessControl: "ბიზნესის კონტროლი",
    businessCalculator: "ბიზნეს კალკულატორი", enterData: "შეიყვანეთ მონაცემები", pureeDose: "პიურეს დოზა", cupPrice: "ერთი ჭიქის გასაყიდი ფასი",
    calculationBasis: "გამოთვლის საფუძველი", pureePrice: "პიურეს ფასი", additionalCost: "დამატებითი ხარჯი", calculationResult: "გამოთვლის შედეგი",
    businessMetrics: "თქვენი ბიზნესის მაჩვენებლები", fromBottle: "ერთი ბოთლიდან", cups: "ჭიქა", cupCost: "ერთი ჭიქის თვითღირებულება",
    includingCosts: "დამატებითი ხარჯების ჩათვლით", cupProfit: "მოგება ერთ ჭიქაზე", perCup: "ყოველი გაყიდული ჭიქიდან", bottleProfit: "სრული მოგება ერთ ბოთლზე", fromSales: "ჭიქის გაყიდვიდან",
    cartTitle: "კალათა", cartEmpty: "კალათა ცარიელია", orderSummary: "შეკვეთის შეჯამება", total: "სულ",
    signInToOrder: "შეკვეთისთვის გაიარეთ ავტორიზაცია ან რეგისტრაცია.", phone: "ტელეფონი", address: "მიწოდების მისამართი", note: "შენიშვნა",
    confirmOrder: "შეკვეთის დადასტურება", sending: "იგზავნება…", viewOrders: "ჩემი შეკვეთები",
    horecaOrderBenefits: "თქვენი HoReCa ბონუსები", iceGift: "ყინული საჩუქრად", estimatedCashback: "სავარაუდო cashback",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("aurevis_language") || "hy");

  useEffect(() => {
    localStorage.setItem("aurevis_language", language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || translations.hy[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
